// Mock data for Hair Track
// Invented factory names & cities — not real businesses

const FACTORIES = [
  {
    id: "FAC-018",
    name: "Qingdao Meilong Hair Industry",
    short: "Meilong",
    city: "Qingdao, Shandong",
    country: "CN",
    specialty: "Raw virgin bundles, closures",
    moq: 50,
    leadTime: 18,
    paymentTerms: "30% T/T, 70% B/L",
    contact: "Lin Wei",
    whatsapp: "+86 138 1042 7788",
    alibaba: "meilonghair.alibaba.com",
    rating: 4.6,
    tier: "A",
    onTime: 0.92,
    orders: 14,
    spend: 82400,
    notes: "Primary bundle supplier. Consistent single-donor quality. Slower on custom lace work.",
    swatch: "#1a1512",
    status: "active",
    samples: 3,
    unread: 2,
  },
  {
    id: "FAC-024",
    name: "Xuchang Arclight Wigs Co.",
    short: "Arclight",
    city: "Xuchang, Henan",
    country: "CN",
    specialty: "HD lace frontals, full wigs",
    moq: 30,
    leadTime: 25,
    paymentTerms: "50/50 T/T",
    contact: "Helen Zhao",
    whatsapp: "+86 159 3722 0411",
    alibaba: "arclightwigs.alibaba.com",
    rating: 4.8,
    tier: "A",
    onTime: 0.96,
    orders: 9,
    spend: 61200,
    notes: "Best HD lace source. Strict on MOQ. Ships via SF Express.",
    swatch: "#3d2b1f",
    status: "active",
    samples: 5,
    unread: 0,
  },
  {
    id: "FAC-031",
    name: "Hebei Crownroot Hair Mfg.",
    short: "Crownroot",
    city: "Xingtai, Hebei",
    country: "CN",
    specialty: "Clip-ins, tape-ins, ponytails",
    moq: 100,
    leadTime: 22,
    paymentTerms: "30/70 T/T",
    contact: "Mei Chen",
    whatsapp: "+86 177 0319 2256",
    alibaba: "crownroot.alibaba.com",
    rating: 4.2,
    tier: "B",
    onTime: 0.81,
    orders: 6,
    spend: 28900,
    notes: "Price-competitive on clip-ins. Packaging needs QC every batch.",
    swatch: "#6b4a32",
    status: "active",
    samples: 2,
    unread: 4,
  },
  {
    id: "FAC-042",
    name: "Guangzhou Velora Beauty",
    short: "Velora",
    city: "Guangzhou, Guangdong",
    country: "CN",
    specialty: "Custom color, balayage, highlights",
    moq: 20,
    leadTime: 14,
    paymentTerms: "100% T/T upfront",
    contact: "Ivy Tan",
    whatsapp: "+86 135 8802 9911",
    alibaba: "velorabeauty.alibaba.com",
    rating: 4.7,
    tier: "A",
    onTime: 0.94,
    orders: 4,
    spend: 19600,
    notes: "Color matching is excellent. Worth the premium for signature shades.",
    swatch: "#9a6b3f",
    status: "active",
    samples: 4,
    unread: 1,
  },
  {
    id: "FAC-055",
    name: "Yiwu Silkbridge Exports",
    short: "Silkbridge",
    city: "Yiwu, Zhejiang",
    country: "CN",
    specialty: "Packaging, boxes, silk pouches",
    moq: 500,
    leadTime: 12,
    paymentTerms: "30/70 T/T",
    contact: "Rachel Gu",
    whatsapp: "+86 189 5710 6633",
    alibaba: "silkbridgepack.alibaba.com",
    rating: 4.4,
    tier: "B",
    onTime: 0.88,
    orders: 3,
    spend: 8200,
    notes: "Soft-touch boxes, gold foil stamping. Color proof turnaround = 4 days.",
    swatch: "#c89968",
    status: "active",
    samples: 2,
    unread: 0,
  },
  {
    id: "FAC-063",
    name: "Chennai Kalpana Tresses",
    short: "Kalpana",
    city: "Chennai, Tamil Nadu",
    country: "IN",
    specialty: "Temple hair, raw Indian bundles",
    moq: 40,
    leadTime: 28,
    paymentTerms: "40/60 T/T",
    contact: "Priya Ramanathan",
    whatsapp: "+91 98404 22117",
    alibaba: "kalpanatresses.alibaba.com",
    rating: 4.3,
    tier: "B",
    onTime: 0.76,
    orders: 2,
    spend: 11400,
    notes: "Authentic temple hair. Lead times slip — build in buffer.",
    swatch: "#d4a574",
    status: "evaluating",
    samples: 1,
    unread: 3,
  },
  {
    id: "FAC-071",
    name: "Shenzhen Haloworks Labs",
    short: "Haloworks",
    city: "Shenzhen, Guangdong",
    country: "CN",
    specialty: "Lace wig prototypes, R&D",
    moq: 10,
    leadTime: 10,
    paymentTerms: "Per-unit, net 15",
    contact: "Kevin Xu",
    whatsapp: "+86 186 6630 2087",
    alibaba: "haloworks.alibaba.com",
    rating: 4.5,
    tier: "A",
    onTime: 0.9,
    orders: 7,
    spend: 14300,
    notes: "Sampling partner of record. Fast iteration, higher per-unit cost.",
    swatch: "#e8d3a8",
    status: "active",
    samples: 6,
    unread: 0,
  },
];

const SAMPLE_STAGES = [
  { id: "requested", label: "Requested", color: "#8a8a85" },
  { id: "in_production", label: "In production", color: "oklch(0.78 0.14 75)" },
  { id: "shipped", label: "Shipped", color: "oklch(0.68 0.17 290)" },
  { id: "received", label: "Received — QC", color: "oklch(0.7 0.14 210)" },
  { id: "approved", label: "Approved", color: "oklch(0.72 0.14 155)" },
  { id: "rejected", label: "Rejected", color: "oklch(0.68 0.18 25)" },
];

const SAMPLES = [
  { id: "S-104", title: "20\" Raw SE Asian bundle, natural 1B", factoryId: "FAC-018", stage: "approved", requested: "Apr 02", eta: "Apr 28", progress: 1.0, swatches: ["#1a1410","#2a1f17"], tracking: "SF 778402116612", cost: 145, notes: "Final batch selected for launch tier 1." },
  { id: "S-108", title: "22\" HD lace frontal 13x6, density 180%", factoryId: "FAC-024", stage: "in_production", requested: "Apr 09", eta: "May 06", progress: 0.55, swatches: ["#1e1611"], tracking: "—", cost: 220 },
  { id: "S-109", title: "Clip-in set 7pc, 18\" honey balayage", factoryId: "FAC-031", stage: "rejected", requested: "Mar 28", eta: "—", progress: 1.0, swatches: ["#3e2c1e","#6b4a2e"], tracking: "—", cost: 95, notes: "Tone ran orange. Revised swatch sent Apr 14." },
  { id: "S-112", title: "Balayage strand test, custom #7N>#22", factoryId: "FAC-042", stage: "received", requested: "Apr 11", eta: "Apr 25", progress: 1.0, swatches: ["#2b1e16","#7a5a3a","#c9a671"], tracking: "DHL 6741-0922-11", cost: 80 },
  { id: "S-115", title: "Soft-touch boxes v3, gold foil 'Halo'", factoryId: "FAC-055", stage: "shipped", requested: "Apr 14", eta: "Apr 24", progress: 0.85, swatches: ["#1a1a1a","#c5a86b"], tracking: "UPS 1Z999X8842", cost: 42 },
  { id: "S-118", title: "Temple hair, 24\" natural black unprocessed", factoryId: "FAC-063", stage: "requested", requested: "Apr 18", eta: "May 16", progress: 0.1, swatches: ["#150f0b"], tracking: "—", cost: 168 },
  { id: "S-120", title: "Prototype halo extension, invisible wire", factoryId: "FAC-071", stage: "in_production", requested: "Apr 13", eta: "Apr 27", progress: 0.7, swatches: ["#2a1f17"], tracking: "—", cost: 135 },
  { id: "S-121", title: "14\" clip-in fringe, bang set 3pc", factoryId: "FAC-031", stage: "requested", requested: "Apr 18", eta: "May 11", progress: 0.05, swatches: ["#1a1410"], tracking: "—", cost: 58 },
  { id: "S-122", title: "22\" full lace wig, bleached knots", factoryId: "FAC-024", stage: "approved", requested: "Mar 20", eta: "Apr 19", progress: 1.0, swatches: ["#1e1611"], tracking: "SF 778490221147", cost: 310, notes: "Hero SKU for launch." },
  { id: "S-123", title: "Revised balayage, custom #4>#20 gradient", factoryId: "FAC-042", stage: "shipped", requested: "Apr 15", eta: "Apr 26", progress: 0.9, swatches: ["#2e2018","#8a6c49","#d4b98a"], tracking: "DHL 6741-0922-77", cost: 88 },
  { id: "S-124", title: "Silk pouch, embossed logo", factoryId: "FAC-055", stage: "received", requested: "Apr 08", eta: "Apr 20", progress: 1.0, swatches: ["#0f0f10"], tracking: "UPS 1Z999X8719", cost: 12 },
  { id: "S-125", title: "Halo prototype v2, nude band", factoryId: "FAC-071", stage: "approved", requested: "Mar 30", eta: "Apr 12", progress: 1.0, swatches: ["#2a1f17","#e8c9a3"], tracking: "—", cost: 140 },
];

const WA_THREADS = [
  {
    id: "w1",
    factoryId: "FAC-018",
    name: "Lin Wei · Meilong",
    handle: "+86 138 1042 7788",
    time: "09:41",
    unread: 2,
    preview: "Sure, we can pull 20\" & 22\" from the same donor. Sending photos now.",
    pinned: true,
    messages: [
      { from: "them", text: "Hi! Following up on sample S-104. Photos attached of the final batch.", ts: "Apr 17 · 14:22", day: "Thursday" },
      { from: "them", img: true, caption: "Final batch — 20\" natural 1B, cuticle-aligned", ts: "Apr 17 · 14:22" },
      { from: "me", text: "These look great. Can you confirm all from same donor? And the weight per bundle?", ts: "Apr 17 · 21:04" },
      { from: "them", text: "Yes all single donor. 100g / bundle, ±2g tolerance.", ts: "Apr 18 · 08:30", day: "Today" },
      { from: "them", text: "Sure, we can pull 20\" & 22\" from the same donor. Sending photos now.", ts: "Apr 18 · 09:41" },
    ],
  },
  {
    id: "w2",
    factoryId: "FAC-031",
    name: "Mei Chen · Crownroot",
    handle: "+86 177 0319 2256",
    time: "08:12",
    unread: 4,
    preview: "The revised swatch is closer but still a little warm. Can you try cooler?",
    messages: [
      { from: "them", text: "Good morning! The revised clip-in set is ready to ship.", ts: "Apr 18 · 08:02", day: "Today" },
      { from: "them", img: true, caption: "Honey balayage — revised batch", ts: "Apr 18 · 08:03" },
      { from: "me", text: "The revised swatch is closer but still a little warm. Can you try cooler?", ts: "Apr 18 · 08:12" },
      { from: "them", text: "Of course. We can adjust to a cooler ash tone. Need 4-5 days.", ts: "Apr 18 · 08:14" },
      { from: "them", text: "Do you want us to hold shipment until new batch is done?", ts: "Apr 18 · 08:14" },
      { from: "them", text: "Payment confirmation received for PO-2041, thank you!", ts: "Apr 18 · 08:20" },
    ],
  },
  {
    id: "w3",
    factoryId: "FAC-024",
    name: "Helen Zhao · Arclight",
    handle: "+86 159 3722 0411",
    time: "Yesterday",
    unread: 0,
    preview: "You: Confirmed, PO-2043 signed. Sending 50% deposit today.",
    messages: [
      { from: "them", text: "Invoice for PO-2043 attached. Lead time 25 days from deposit.", ts: "Apr 17 · 10:15", day: "Yesterday" },
      { from: "me", text: "Confirmed, PO-2043 signed. Sending 50% deposit today.", ts: "Apr 17 · 15:40" },
    ],
  },
  {
    id: "w4",
    factoryId: "FAC-042",
    name: "Ivy Tan · Velora",
    handle: "+86 135 8802 9911",
    time: "Yesterday",
    unread: 1,
    preview: "Tracking: DHL 6741-0922-77. Should arrive Apr 26.",
    messages: [
      { from: "them", text: "Revised balayage sample has shipped today.", ts: "Apr 17 · 17:02", day: "Yesterday" },
      { from: "them", text: "Tracking: DHL 6741-0922-77. Should arrive Apr 26.", ts: "Apr 17 · 17:02" },
    ],
  },
  {
    id: "w5",
    factoryId: "FAC-063",
    name: "Priya R. · Kalpana",
    handle: "+91 98404 22117",
    time: "Mon",
    unread: 3,
    preview: "We have temple hair batch from last weekend's collection. 24\"+ available.",
    messages: [
      { from: "them", text: "Namaste! We have temple hair batch from last weekend's collection. 24\"+ available.", ts: "Apr 15 · 11:20", day: "Monday" },
      { from: "them", text: "Can offer 40kg total. Single-origin, unprocessed.", ts: "Apr 15 · 11:21" },
      { from: "them", text: "Pricing sheet attached. Let me know sample quantity needed.", ts: "Apr 15 · 11:22" },
    ],
  },
  {
    id: "w6",
    factoryId: "FAC-055",
    name: "Rachel Gu · Silkbridge",
    handle: "+86 189 5710 6633",
    time: "Sat",
    unread: 0,
    preview: "You: Looks good, proceed to production.",
    messages: [
      { from: "them", text: "Proof v3 for boxes attached. Gold foil is 24k equivalent.", ts: "Apr 13 · 09:10", day: "Saturday" },
      { from: "me", text: "Looks good, proceed to production.", ts: "Apr 13 · 09:45" },
    ],
  },
  {
    id: "w7",
    factoryId: "FAC-071",
    name: "Kevin Xu · Haloworks",
    handle: "+86 186 6630 2087",
    time: "Apr 14",
    unread: 0,
    preview: "Prototype v2 approved — moving to v3 with softer band.",
    messages: [
      { from: "me", text: "Prototype v2 approved — moving to v3 with softer band.", ts: "Apr 14 · 16:30", day: "Apr 14" },
      { from: "them", text: "Got it. v3 start tomorrow. Target ETA Apr 27.", ts: "Apr 14 · 16:45" },
    ],
  },
];

const INVOICES = [
  {
    id: "INV-2043",
    file: "arclight-PO2043-invoice.pdf",
    factoryId: "FAC-024",
    date: "Apr 17, 2026",
    amount: 12480,
    currency: "USD",
    status: "parsed",
    confidence: 0.97,
    parsing: false,
    fields: {
      factory: "Xuchang Arclight Wigs Co.",
      poNumber: "PO-2043",
      invoiceNumber: "AR-2026-0413",
      date: "2026-04-17",
      dueDate: "2026-05-17",
      terms: "50/50 T/T",
      subtotal: 12000,
      shipping: 320,
      tax: 160,
      total: 12480,
      currency: "USD",
      bank: "Bank of China, Xuchang Branch",
      swift: "BKCHCNBJ300",
      account: "1234 **** **** 7788",
    },
    lines: [
      { sku: "AR-HDL-22-180", desc: "22\" HD Lace Frontal Wig, 180% density, natural 1B", qty: 30, unit: 380, total: 11400 },
      { sku: "AR-HDL-CLS-5x5", desc: "5x5 HD Lace Closure, 18\", natural 1B", qty: 10, unit: 60, total: 600 },
    ],
  },
  {
    id: "INV-2041",
    file: "crownroot-PO2041-invoice.pdf",
    factoryId: "FAC-031",
    date: "Apr 12, 2026",
    amount: 4850,
    currency: "USD",
    status: "approved",
    confidence: 0.94,
    fields: { factory: "Hebei Crownroot Hair Mfg.", poNumber: "PO-2041", invoiceNumber: "CR-0412-118", date: "2026-04-12", dueDate: "2026-05-12", terms: "30/70 T/T", total: 4850, currency: "USD" },
    lines: [],
  },
  {
    id: "INV-2045",
    file: "meilong-proforma-20Apr.pdf",
    factoryId: "FAC-018",
    date: "Apr 20, 2026",
    amount: 8720,
    currency: "USD",
    status: "needs_review",
    confidence: 0.82,
    fields: { factory: "Qingdao Meilong Hair Industry", poNumber: "PO-2045", invoiceNumber: "ML-20260420", date: "2026-04-20", dueDate: "2026-05-20", terms: "30/70 T/T", total: 8720, currency: "USD" },
    lines: [],
  },
  {
    id: "INV-2039",
    file: "velora-sample-invoice-Apr.pdf",
    factoryId: "FAC-042",
    date: "Apr 11, 2026",
    amount: 168,
    currency: "USD",
    status: "parsed",
    confidence: 0.99,
    fields: { factory: "Guangzhou Velora Beauty", poNumber: "SAMPLE", invoiceNumber: "VL-041126", date: "2026-04-11", dueDate: "2026-04-25", terms: "100% T/T", total: 168, currency: "USD" },
    lines: [],
  },
  {
    id: "INV-2036",
    file: "silkbridge-proof-invoice.pdf",
    factoryId: "FAC-055",
    date: "Apr 08, 2026",
    amount: 2150,
    currency: "USD",
    status: "approved",
    confidence: 0.96,
    fields: { factory: "Yiwu Silkbridge Exports", poNumber: "PO-2036", invoiceNumber: "SB-0408", date: "2026-04-08", dueDate: "2026-05-08", terms: "30/70 T/T", total: 2150, currency: "USD" },
    lines: [],
  },
];

const TIMELINE_ITEMS = [
  // weeks are 0..11 representing Apr-W1 through Jun-W4
  { id: "T1", label: "Meilong — 20\"/22\" bundles", factory: "FAC-018", start: 0, end: 3, status: "ok", phase: "Sample" },
  { id: "T2", label: "Arclight — HD lace frontals", factory: "FAC-024", start: 1, end: 6, status: "ok", phase: "Production" },
  { id: "T3", label: "Crownroot — clip-ins v2", factory: "FAC-031", start: 2, end: 5, status: "warn", phase: "Rework" },
  { id: "T4", label: "Velora — custom balayage", factory: "FAC-042", start: 2, end: 4, status: "ok", phase: "Sample" },
  { id: "T5", label: "Silkbridge — boxes + pouches", factory: "FAC-055", start: 3, end: 6, status: "ok", phase: "Production" },
  { id: "T6", label: "Kalpana — temple hair sourcing", factory: "FAC-063", start: 2, end: 7, status: "warn", phase: "Evaluation" },
  { id: "T7", label: "Haloworks — halo prototype v3", factory: "FAC-071", start: 3, end: 5, status: "ok", phase: "Sample" },
  { id: "T8", label: "Launch prep — photography", factory: "—", start: 6, end: 8, status: "ok", phase: "Marketing" },
  { id: "T9", label: "Warehouse intake + QC", factory: "—", start: 7, end: 9, status: "ok", phase: "Ops" },
  { id: "T10", label: "Public launch · 1B line", factory: "—", start: 9, end: 10, status: "accent", phase: "Launch" },
  { id: "T11", label: "Restock wave 1", factory: "—", start: 10, end: 12, status: "ok", phase: "Restock" },
];

const WEEKS = [
  "Apr W1","Apr W2","Apr W3","Apr W4","May W1","May W2","May W3","May W4","Jun W1","Jun W2","Jun W3","Jun W4"
];

const COST_ROWS = [
  { sku: "HALO-1B-20", name: "Halo extension — 20\" natural 1B", factory: "FAC-071", unitCost: 46.20, retail: 189, margin: 0.76, qty: 250 },
  { sku: "HDL-1B-22", name: "HD lace frontal wig — 22\" 1B", factory: "FAC-024", unitCost: 142.80, retail: 499, margin: 0.71, qty: 120 },
  { sku: "BND-RAW-20", name: "Raw bundle — 20\" natural", factory: "FAC-018", unitCost: 58.40, retail: 179, margin: 0.67, qty: 400 },
  { sku: "CLP-7P-18", name: "Clip-in set 7pc — 18\"", factory: "FAC-031", unitCost: 38.00, retail: 149, margin: 0.75, qty: 300 },
  { sku: "BAL-CUS-22", name: "Custom balayage — 22\"", factory: "FAC-042", unitCost: 96.00, retail: 329, margin: 0.71, qty: 80 },
  { sku: "PKG-BOX-A", name: "Signature box + pouch", factory: "FAC-055", unitCost: 4.20, retail: 0, margin: 0, qty: 1500 },
];

const ACTIVITY = [
  { time: "09:41", who: "Lin Wei", what: <>Replied in <b>S-104 · Meilong</b> — confirmed single-donor 20\" & 22\".</> },
  { time: "09:12", who: "Mia K.", what: <>Approved <b>INV-2041</b> from Crownroot. Payment scheduled.</> },
  { time: "08:30", who: "System", what: <>Auto-parsed invoice <b>arclight-PO2043-invoice.pdf</b>, 97% confidence.</> },
  { time: "08:12", who: "Mei Chen", what: <>Sent 3 messages re. <b>S-103 clip-in set</b> color revision.</> },
  { time: "Yday", who: "Helen Zhao", what: <>Confirmed <b>PO-2043</b> signed, lead time 25d.</> },
  { time: "Yday", who: "Ivy Tan", what: <>Shipped <b>S-123 balayage</b> via DHL, ETA Apr 26.</> },
  { time: "Mon", who: "Priya R.", what: <>Offered temple hair batch, 40kg available.</> },
];

// Expose to other scripts
Object.assign(window, { FACTORIES, SAMPLE_STAGES, SAMPLES, WA_THREADS, INVOICES, TIMELINE_ITEMS, WEEKS, COST_ROWS, ACTIVITY });
